pull_request_rules:
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: warn on needs-work
    conditions:
      - "#check-failure>=1"
    actions:
      comment:
        message: "@{{author}} this pull request has failed checks 🛠"
      label:
        add:
          - needs-work
  - name: remove needs-work label if not needed
    conditions:
      - check-success=Lint
      - check-success=Snapshot
      - check-success=Test on Linux
      - check-success=Test on MacOS
      - check-success=codecov/patch
      - check-success=codecov/project    
    actions:
      label:
        remove:
          - needs-work
  - name: Automatic maintainer assignment
    conditions:
      - -conflict
      - check-success=Lint
      - check-success=Snapshot
      - check-success=Test on Linux
      - check-success=Test on MacOS
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      request_reviews:
        teams: 
        - "@nektos/act-maintainers"
  - name: Automatic committer assignment
    conditions:
      - "approved-reviews-by=@nektos/act-maintainers"
      - -conflict
      - check-success=Lint
      - check-success=Snapshot
      - check-success=Test on Linux
      - check-success=Test on MacOS
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      request_reviews:
        teams: 
        - "@nektos/act-committers"
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by=@nektos/act-committers"
      - check-success=Lint
      - check-success=Snapshot
      - check-success=Test on Linux
      - check-success=Test on MacOS
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      merge:
        method: squash