name: basic
on: push

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:10.16-jessie
      env:
        NODE_ENV: development
    steps:
      - run: env
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: cp $GITHUB_EVENT_PATH $HOME/foo.json
    - run: ls $HOME
    - run: cat $HOME/foo.json
    - uses: docker://alpine:3.8
      with:
        args: uname -a
  local-action:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/docker-url

